[".config/spicetify/Themes/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/spicetify/archive/refs/heads/main.tar.gz"
  stripComponents = 3
  refreshPeriod = "336h"
  include = ["*/catppuccin/**"]

[".config/kitty/catppuccin-mocha.conf"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/kitty/refs/heads/main/themes/mocha.conf"
  refreshPeriod = "336h"

[".config/micro/colorschemes/catppuccin-mocha-transparent.micro"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/micro/refs/heads/main/themes/catppuccin-mocha-transparent.micro"
  refreshPeriod = "336h"

[".zen/default/chrome"]
  type = "archive"
  url = "https://github.com/catppuccin/zen-browser/archive/refs/heads/main.tar.gz"
  stripComponents = 3
  refreshPeriod = "336h"
  include = ["*/themes/Mocha/Mauve/**"]

[".config/Kvantum/catppucin-mocha-mauve"]
  type = "archive"
  url = "https://github.com/catppuccin/kvantum/archive/refs/heads/main.tar.gz"
  stripComponents = 3
  refreshPeriod = "336h"
  include = ["*/themes/catppuccin-mocha-mauve/**"]

[".config/bat/Catppuccin Mocha.tmTheme"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/bat/refs/heads/main/themes/Catppuccin%20Mocha.tmTheme"
  refreshPeriod = "336h"

[".config/btop/themes/catppuccin_mocha.theme"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/btop/refs/heads/main/themes/catppuccin_mocha.theme"
  refreshPeriod = "336h"

[".config/cava/config"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/cava/refs/heads/main/themes/mocha-transparent.cava"
  refreshPeriod = "336h"

[".config/hypr/colors.conf"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/hyprland/refs/heads/main/themes/mocha.conf"
  refreshPeriod = "336h"

[".config/yazi/theme.toml"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/yazi/refs/heads/main/themes/mocha/catppuccin-mocha-mauve.toml"
  refreshPeriod = "336h"

[".config/waybar/logo.png"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/catppuccin/main/assets/logos/exports/1544x1544_circle.png"
  refreshPeriod = "336h"

[".config/wlogout/catppuccin-mocha-mauve.css"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/wlogout/refs/heads/main/themes/mocha/mauve.css"
  refreshPeriod = "336h"

[".config/wlogout/icons"]
  type = "archive"
  url = "https://github.com/catppuccin/wlogout/archive/refs/heads/main.tar.gz"
  stripComponents = 4
  refreshPeriod = "336h"
  include = ["*/icons/wlogout/mocha/mauve/**"]